# Generated by Django 3.2.7 on 2021-12-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211213_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unavailable', 'Unavailable'), ('On Test Drive', 'On Test Drive'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sadan', 'Sadan'), ('SUV', 'SUV')], max_length=200, null=True),
        ),
    ]
